style: format with Ruff
biocommons/bioutils pull request #65
Opened 2024-06-05 13:38 UTC by jsstevenson

2024-06-20 02:45 UTC, korikuzma requested changes
@jsstevenson do you plan on adding a `.git-blame-ignore-revs` file? More [here](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)

2024-06-20 02:45 UTC, korikuzma commented on pyproject.toml
> +src = ["src", "test"]
```suggestion
src = ["src", "tests"]
```

2024-06-21 12:10 UTC, jsstevenson commented
@korikuzma sure, the # of changes is fairly minimal but we can

2024-06-21 12:25 UTC, korikuzma commented on pyproject.toml
> +src = ["src", "test"]
@jsstevenson Should this be resolved?

2024-06-21 12:25 UTC, korikuzma commented
> @korikuzma sure, the # of changes is fairly minimal but we can

@jsstevenson Ya, I think it'd be good to do for all the other ruff format PRs too

2024-06-26 11:24 UTC, korikuzma commented on pyproject.toml
> +src = ["src", "test"]
This PR is still showing up in https://github.com/pulls/review-requested for me. See above comment

2024-06-26 11:25 UTC, korikuzma reviewed
See thread above (trying to remove from my requested reviews)

2024-06-26 12:18 UTC, jsstevenson commented
ope didn't commit

2024-06-26 12:39 UTC, korikuzma approved these changes

2024-06-26 12:44 UTC, merged